### PR TITLE
Beautify with Jekyll

### PR DESCRIPTION
**Pull request by neila-a**
The original is a little ugly, isn't it?

### CODE REVIEW

**Comment by mhtvsSFrpHdE** [comment]
Save patch for later confirm

**Comment by neila-a** [comment]
Who will save the patch?

**Comment by mhtvsSFrpHdE** [comment]
> Who will save the patch?

I don't know, currently there is no active maintainer

**Comment by neila-a** [comment]
I just want to make sure that I am not the one to finish the work.

**Pull request merged**
